#!/usr/bin/env bash

main() {
  transform_carriage_return_to_new_line
  rename_headers
  latin1_to_utf8
}

rename_headers() {
  # States
  sed -i 's/CVE_ENT/code/g' datasets/states.csv
  sed -i 's/NOM_ENT/name/g' datasets/states.csv

  # Municipalities
  sed -i 's/CVE_ENT/state_code/g' datasets/municipalities.csv
  sed -i 's/CVE_MUN/municipality_code/g' datasets/municipalities.csv
  sed -i 's/NOM_MUN/name/g' datasets/municipalities.csv

  # Localities
  sed -i 's/CVE_ENT/state_code/g' datasets/localities.csv
  sed -i 's/CVE_MUN/municipality_code/g' datasets/localities.csv
  sed -i 's/CVE_LOC/locality_code/g' datasets/localities.csv
  sed -i 's/NOM_LOC/name/g' datasets/localities.csv
  sed -i 's/AMBITO/area/g' datasets/localities.csv
}

transform_carriage_return_to_new_line() {
  for dataset in datasets/*.csv; do
    sed -i 's/\r/\n/g' ${dataset}
  done
}

latin1_to_utf8() {
  for dataset in datasets/*.csv; do
    iconv -f ISO-8859-1 -t UTF-8 ${dataset} -o ${dataset}.tmp
    mv ${dataset}.tmp ${dataset}
    rm ${dataset}.tmp
  done
}

main
